version: 1
disable_existing_loggers: no

formatters:
  info:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s at %(filename)s line %(lineno)d'
  verbose:
    format: '[%(asctime)s] [%(levelname)s] %(module)s - %(message)s at %(filename)s line %(lineno)d'

handlers:
  console:
    class: logging.StreamHandler
    formatter: info
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: verbose
    filename: 'app.log'

loggers:
  root:
    level: INFO
    handlers: [console]

  __name__:
    propagate: yes
