"""empty message

Revision ID: 11f8320e6954
Revises: 7c5052cccfa5
Create Date: 2025-03-27 16:29:14.957696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f8320e6954'
down_revision: Union[str, None] = '7c5052cccfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('token_multiplier', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'token_multiplier')
    # ### end Alembic commands ###
