"""empty message

Revision ID: d140ada0b1dd
Revises: fb705712f1ab
Create Date: 2025-03-05 11:42:57.816096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd140ada0b1dd'
down_revision: Union[str, None] = 'fb705712f1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transactions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tokens_amount', sa.Integer(), nullable=False),
        sa.Column(
            'cause',
            sa.Enum(
                'purchase', 'refund', 'translation', name='balancechangecause'
            ),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    op.execute('UPDATE USERS SET balance = 0')
    op.alter_column('users', 'balance', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_column('users', 'balance')
    op.execute('DROP TYPE IF EXISTS balancechangecause')
    # ### end Alembic commands ###
