services:
    g4f:
        image: hlohaus789/g4f:latest
        volumes:
            - /home/Aleh/gpt4free/g4f:/app/g4f
        ports:
            - 1337:1337
            - 8080:8080
        networks:
            - a

networks:
  a:
    external: true
